apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ServiceName-ManagerApi
  labels:
    app: swisschain-service-name-managerapi
    environment: Development
    tier: Service
  name: swisschain-service-name-managerapi
  namespace: swisschain-product-name
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: swisschain-service-name-managerapi
  template:
    metadata:
      labels:
        app: swisschain-service-name-managerapi
      name: swisschain-service-name-managerapi
    spec:
      containers:
      - name: swisschain-service-name-managerapi
        image: docker.io/swisschains/swisschain-product-name-swisschain-service-name-managerapi:dev
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: RemoteSettingsUrls__0 
          value: "http://settings.common.svc.cluster.local/common"
        - name: RemoteSettingsUrls__1 
          value: "http://settings.common.svc.cluster.local/swisschain-product-name/common"
        - name: RemoteSettingsUrls__2
          value: "http://settings.common.svc.cluster.local/swisschain-product-name/swisschain-service-name"