name: Release Service

on:
  push:
    tags: "service-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/service-}
    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Publish Manager API
      run: dotnet publish ./src/ServiceName.ManagerApi/ServiceName.ManagerApi.csproj --output ./publish-api --configuration Release
    - name: Publish Datareader API
      run: dotnet publish ./src/ServiceName.DataReaderApi/ServiceName.DataReaderApi.csproj --output ./publish-datareader-api --configuration Release
    - name: Publish worker
      run: dotnet publish ./src/ServiceName.Worker/ServiceName.Worker.csproj --output ./publish-worker --configuration Release

    - name: Check Manager API dir
      run: ls ./publish-api
    - name: Check DataReader API dir
      run: ls ./publish-datareader-api
    - name: Check worker dir
      run: ls ./publish-worker

    - name: Publish Manager API to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/swisschain-product-name-swisschain-service-name-managerapi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
        tag_name_skip: service-    
    - name: Publish DataReader API to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/swisschain-product-name-swisschain-service-name-datareaderapi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-datareader-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
        tag_name_skip: service-    
    - name: Publish worker to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/swisschain-product-name-swisschain-service-name-worker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-worker
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
        tag_name_skip: service-
